---
title: "Lab 06 - Functions and iterations"
author: "Muhammad Sami Munawar"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
```

```{r diamon_rename}
diamonds <- diamonds %>% rename(
    depth_pct = depth,
    length_mm = x,
    width_mm = y,
    depth_mm = z,
    table_pct = table
  )

diamonds

```


## Exercise 1

```{r}
# Do some preliminary investigations & cleaning

# diamonds %>% count(cut) 

diamonds <- diamonds %>% filter(length_mm != 0, width_mm != 0, depth_mm != 0, na.rm = TRUE) 

summary(diamonds)

ggplot(diamonds, aes(x = length_mm, y = depth_pct)) + geom_point() # 
ggplot(diamonds, aes(x = width_mm, y = depth_pct)) + geom_point()
ggplot(diamonds, aes(x = depth_mm, y = depth_pct)) + geom_point()
```


## Exercise 2

```{r}

diamonds <- diamonds %>%
  mutate(table_mm = table_pct * width_mm / 100)


# Overall table_mm arithmetic mean?
mean <- function(x){
  count <- 0
  total <- total + x
  count <- count + 1 
  return(total/count)
}
mean(diamonds$table_mm)


# table_mm arithmetic mean within each clarity category



```

_Add your comment here_

## Exercise 3

_Do derivation on paper, unless you know how to write LaTeX code_


## Exercise 4

```{r}
# Write gmean() command

gmean <- function(x){
  n = 0
  sum = 0
  n = n + 1
  sum = log(x) + sum 
  gmean = exp(1/n * sum)
  return(gmean)
}

gmean(diamonds$table_mm)


```

## Exercise 5

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", "7", "8")
)


# Create for loop to test gmean() on the above examples


```


## Exercise 6

```{r}
# Copy gmean() from Ex4 and edit it to check the input





# Copy your code from Ex 5 to test your new command





```


## Exercise 7

```{r}
# Overall table_mm geometic mean?






# table_mm geometic mean within each clarity category






```

_Add your comment here_


## Exercise 8 (optional)

```{r}
# Create gmean2() that computes the geometric mean 
#   that uses the original definition






```


## Exercise 9 (optional)

```{r}
# Create a function that computes the harmonic mean







```
